### ISSUE TITLE
previously working installation fails

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#15]
I tried to install the new version on Linux Mint machine: 
`pip ` worked fine, but then: 

`(openpivgui) user@Turbo-NUC7:~/Downloads/fix_opentpv/notebooks$ python -m openpivgui.OpenPivGui
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/site-packages/openpivgui/OpenPivGui.py", line 801, in <module>
    openPivGui = OpenPivGui()
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/site-packages/openpivgui/OpenPivGui.py", line 96, in __init__
    self.iconphoto(False, tk.PhotoImage(file = self.icon_path)) # convert .png into a usable icon photo
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/tkinter/__init__.py", line 4061, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/home/user/miniconda3/envs/openpivgui/lib/python3.8/tkinter/__init__.py", line 4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/user/miniconda3/envs/openpivgui/lib/python3.8/site-packages/openpivgui/../openpivgui/test.png": no such file or directory
`

**Comment by eguvep** [comment]
Just fixed! Thanks for reporting!
