### ISSUE TITLE
Linux Mint 19 installation fails

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_tk_gui#32]
(test) user@Turbo-NUC7:~$ python -m openpivgui.OpenPivGui
Initializing GUI
Initializing widgets
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda3/envs/test/lib/python3.9/site-packages/openpivgui/OpenPivGui.py", line 1222, in <module>
    openPivGui = OpenPivGui()
  File "/home/user/miniconda3/envs/test/lib/python3.9/site-packages/openpivgui/OpenPivGui.py", line 117, in __init__
    self.__init_widgets()
  File "/home/user/miniconda3/envs/test/lib/python3.9/site-packages/openpivgui/OpenPivGui.py", line 337, in __init_widgets
    self.__init_vec_colorpicker(key)
  File "/home/user/miniconda3/envs/test/lib/python3.9/site-packages/openpivgui/OpenPivGui.py", line 966, in __init_vec_colorpicker
    self.valid_color = tk.Button(f,
  File "/home/user/miniconda3/envs/test/lib/python3.9/tkinter/__init__.py", line 2650, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "/home/user/miniconda3/envs/test/lib/python3.9/tkinter/__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name "None"

**Comment by eguvep** [comment]
Could you please try to remove the configuration file »open_piv_gui.json« from your home directory, and see, if the GUI starts?
If this works, the error might have been the following:
When the color picker for the valid and invalid vector color on the plotting tab was left with cancel, the color was set to None. I removed this behavior in v0.4.4. So this should not happen again.

**Comment by alexlib** [comment]
Thanks. It solved the installation issue. Will try to remember it in the future. Maybe to add it to the Wiki or documentation?

**Comment by eguvep** [comment]
Fine. This behavior is not possible from v0.4.4 on. The color value will never be None again, even if you close the color-picker with cancel.
